/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import prog2.controlador.Controlador;
import prog2.model.Comanda;

/**
 *
 * @author Pablo
 */
public class FrmGestioComandes extends javax.swing.JFrame {

    Controlador _controlador;

    /**
     * Creates new form FrmGestioComandes
     *
     * @param control
     */
    public FrmGestioComandes(Controlador control) {
        initComponents();
        _controlador = control;
        this.frameAfegir.setVisible(false);
        actualitzarComandes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        llistaComandes = new javax.swing.JList<>();
        boxMostrarUrgents = new javax.swing.JCheckBox();
        btnAfegirComanda = new javax.swing.JButton();
        btnEsborrarComanda = new javax.swing.JButton();
        btnSortir = new javax.swing.JButton();
        frameAfegir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        llistaArticles = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        llistaClients = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtQuantitat = new javax.swing.JTextField();
        btnAfegir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        boxUrgent = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(llistaComandes);

        boxMostrarUrgents.setText("Només urgents");
        boxMostrarUrgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMostrarUrgentsActionPerformed(evt);
            }
        });

        btnAfegirComanda.setText("Afegir Comanda");
        btnAfegirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirComandaActionPerformed(evt);
            }
        });

        btnEsborrarComanda.setText("Esborrar Comanda");

        btnSortir.setText("Sortir");

        jLabel1.setText("Selecciona un Article:");

        jScrollPane2.setViewportView(llistaArticles);

        jScrollPane3.setViewportView(llistaClients);

        jLabel2.setText("Selecciona un Client:");

        jLabel3.setText("Quantitat: ");

        btnAfegir.setText("Afegir");
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        boxUrgent.setText("És urgent");

        javax.swing.GroupLayout frameAfegirLayout = new javax.swing.GroupLayout(frameAfegir);
        frameAfegir.setLayout(frameAfegirLayout);
        frameAfegirLayout.setHorizontalGroup(
            frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAfegirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAfegirLayout.createSequentialGroup()
                        .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(frameAfegirLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameAfegirLayout.createSequentialGroup()
                                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxUrgent)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAfegir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frameAfegirLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        frameAfegirLayout.setVerticalGroup(
            frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAfegirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameAfegirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAfegir)
                        .addGap(31, 31, 31)
                        .addComponent(btnCancelar)
                        .addGap(25, 25, 25))
                    .addGroup(frameAfegirLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxUrgent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(frameAfegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boxMostrarUrgents)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(frameAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEsborrarComanda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(btnAfegirComanda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSortir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnAfegirComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEsborrarComanda)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boxMostrarUrgents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frameAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualitzarComandes() {
        if (_controlador.recuperarComandes() != null) {
            DefaultListModel<String> list = new DefaultListModel<>();
            Iterator<String> it = _controlador.recuperarComandes().iterator();
            while (it.hasNext()) {
                list.addElement(it.next());
            }
            this.llistaComandes.setModel(list);
        } else {
            DefaultListModel<String> list = new DefaultListModel<>();
            list.addElement("No hi ha Comandes");
            llistaComandes.setModel(list);
        }
    }

    private void boxMostrarUrgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMostrarUrgentsActionPerformed
        if (!this.boxMostrarUrgents.isSelected()) {
            actualitzarComandes();
        } else {
            if (_controlador.recuperarComandesUrgents() != null) {
                DefaultListModel<String> list = new DefaultListModel<>();
                Iterator<String> it = _controlador.recuperarComandesUrgents().iterator();
                while (it.hasNext()) {
                    list.addElement(it.next());
                }
                this.llistaComandes.setModel(list);
            } else {
                DefaultListModel<String> list = new DefaultListModel<>();
                list.addElement("No hi ha Comandes");
                llistaComandes.setModel(list);
            }
        }
    }//GEN-LAST:event_boxMostrarUrgentsActionPerformed

    private void btnAfegirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirComandaActionPerformed
        this.frameAfegir.setVisible(true);
        if (_controlador.recuperarArticles() != null) {
            DefaultListModel<String> list = new DefaultListModel<>();
            Iterator<String> it = _controlador.recuperarArticles().iterator();
            while (it.hasNext()) {
                list.addElement(it.next());
            }
            this.llistaArticles.setModel(list);
        } else {
            DefaultListModel<String> list = new DefaultListModel<>();
            list.addElement("No hi han articles");
            llistaArticles.setModel(list);
        }

        if (_controlador.recuperarClients() != null) {
            DefaultListModel<String> list = new DefaultListModel<>();
            Iterator<String> it = _controlador.recuperarClients().iterator();
            while (it.hasNext()) {
                list.addElement(it.next());
            }
            this.llistaClients.setModel(list);
        } else {
            DefaultListModel<String> list = new DefaultListModel<>();
            list.addElement("No hi ha clients");
            llistaClients.setModel(list);
        }

    }//GEN-LAST:event_btnAfegirComandaActionPerformed

    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        try {
            int articlePos = this.llistaArticles.getSelectedIndex();
            int clientPos = this.llistaClients.getSelectedIndex();
            int quantitat = Integer.parseInt(this.txtQuantitat.getText());
            boolean esUrgent = this.boxUrgent.isSelected();
            _controlador.addComanda(articlePos, clientPos, quantitat, esUrgent);
        } catch (MercatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Informació d'errors", JOptionPane.ERROR_MESSAGE);
        }
        this.actualitzarComandes();
        
    }//GEN-LAST:event_btnAfegirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxMostrarUrgents;
    private javax.swing.JCheckBox boxUrgent;
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnAfegirComanda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEsborrarComanda;
    private javax.swing.JButton btnSortir;
    private javax.swing.JPanel frameAfegir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> llistaArticles;
    private javax.swing.JList<String> llistaClients;
    private javax.swing.JList<String> llistaComandes;
    private javax.swing.JTextField txtQuantitat;
    // End of variables declaration//GEN-END:variables
}
