/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prog2.vista;

import java.util.Iterator;
import javax.swing.DefaultListModel;
import prog2.controlador.Controlador;

/**
 *
 * @author Pablo
 */
public class FrmGestioClients extends javax.swing.JFrame {

    /**
     * Creates new form FrmGestioClients
     */
    
    Controlador _controlador;
    
    public FrmGestioClients(Controlador controlador) {
        initComponents();
        _controlador = controlador;
        actualitzarClients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        llistaClients = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnAfegirClient = new javax.swing.JButton();
        btnExitActionPerformed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(llistaClients);

        jLabel1.setText("Llista Clients");

        btnAfegirClient.setText("Afegir Client");
        btnAfegirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirClientActionPerformed(evt);
            }
        });

        btnExitActionPerformed.setText("Sortir");
        btnExitActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitActionPerformed))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAfegirClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAfegirClient)))
                .addGap(18, 18, 18)
                .addComponent(btnExitActionPerformed)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfegirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirClientActionPerformed
        FrmAfegirClient frame = new FrmAfegirClient(_controlador, this);
        frame.setVisible(true);
    }//GEN-LAST:event_btnAfegirClientActionPerformed

    private void btnExitActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformedActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformedActionPerformed

    public void actualitzarClients() {
        if (_controlador.recuperarClients() != null) {
            DefaultListModel<String> list = new DefaultListModel<>();
            Iterator<String> it = _controlador.recuperarClients().iterator();
            while (it.hasNext()) {
                list.addElement(it.next());
            }
            this.llistaClients.setModel(list);
        } else {
            DefaultListModel<String> list = new DefaultListModel<>();
            list.addElement("No hi ha clients");
            llistaClients.setModel(list);
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirClient;
    private javax.swing.JButton btnExitActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> llistaClients;
    // End of variables declaration//GEN-END:variables
}
